### ISSUE TITLE
PluginAPI Suggestion: playerSleep() Interface

### ISSUE THREAD

**Issue by ATXLtheAxolotl** [NobUwU/BeRP#34]
I recommend for the pluginAPI that there should be an interface for detecting when players sleep, when they wake up, got forced to be woken up (by taking damage while sleeping) and when cats deliver gifts. I recommend this so that the pluginAPI is more extensive.

**Comment by PMK744** [comment]
Solution can be found here, https://github.com/MCBE-Utilities/BeAPI
