### ISSUE TITLE
[Idea] Entities.ts, Item.ts nbts, and Block.ts nbts.

### ISSUE THREAD

**Issue by ATXLtheAxolotl** [NobUwU/BeRP#45]
I’m not quite sure what PMK744 is doing with Blocks and items .ts but the next most logical file would be Entities.ts and maybe add nbts to the items and block typescript files.

**Comment by NobUwU** [comment]
Packets send runtime ids and interger representations for blocks, items, and entities. He is making files to translate the integer to something more kid friendly for plugin developers.

We have no plans on adding typings for nbt as nbt is just json, if you wish to use nbt then include it in whatever packet you are attempting to send.

Our interfaces have nbt typed as `any` and or `Record<any, any>` thus there should be no type conflicts/collisions when attempting to declare nbt.
